"""Release-template checks; run with NAM2ZOOM_TEMPLATE_DIR pointing at generated templates."""

import hashlib
import json
import os
from pathlib import Path
import shutil
import struct
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from elf32 import parse_elf32
from zd2 import parse_zd2_bytes
from nam2zoom.bank import prepare_bank, WORDS_PER_MODEL
from nam2zoom.template import fill_template

TEMPLATES = os.environ.get("NAM2ZOOM_TEMPLATE_DIR")


@unittest.skipUnless(TEMPLATES, "release templates are generated by the maintainer")
class TemplateTests(unittest.TestCase):
    def test_local_pedal_tested_image_is_preserved(self):
        if os.environ.get("NAM2ZOOM_HARDWARE_TEST_CANDIDATE") == "1":
            self.skipTest("explicit hardware-test candidate; audition before updating the baseline")
        candidate = ROOT / ".tooling/model-selection-baseline-20261001"
        if not (candidate / "build/N2ZBANK.ZD2").is_file():
            self.skipTest("local pedal-tested bank is not distributed")
        lock = json.loads((candidate / "bank.json").read_text())
        weights = (candidate / "weights.f32").read_bytes()
        stride = WORDS_PER_MODEL * 4
        models = [(Path(row["source"]), row["label"],
                   weights[i * stride:(i + 1) * stride], row["source_sha256"])
                  for i, row in enumerate(lock["models"])]
        with tempfile.TemporaryDirectory() as temporary:
            manifest = prepare_bank(models, Path(temporary) / "bank")
            built = fill_template(Path(TEMPLATES), manifest)
            expected = parse_zd2_bytes((candidate / "build/N2ZBANK.ZD2").read_bytes())
            actual = parse_zd2_bytes(built.read_bytes())
            if actual.data_chunk.data != expected.data_chunk.data:
                actual_hash = hashlib.sha256(actual.data_chunk.data).hexdigest()
                expected_hash = hashlib.sha256(expected.data_chunk.data).hexdigest()
                self.fail(
                    "generated DSP differs from the local pedal-tested image; "
                    "hardware audition and an explicitly updated baseline are required "
                    f"before release (generated {actual_hash}, tested {expected_hash})"
                )

    def models(self, count):
        weights = struct.pack(f"<{WORDS_PER_MODEL}f", *([0.03125] * WORDS_PER_MODEL))
        return [(Path(__file__), f"AMP{i+1}", weights, "fixture") for i in range(count)]

    def test_every_capacity_changes_data_not_code(self):
        directory = Path(TEMPLATES)
        index = json.loads((directory / "index.json").read_text())
        for count in range(1, 6):
            with self.subTest(count=count), tempfile.TemporaryDirectory() as temp:
                models = self.models(count)
                manifest = prepare_bank(models, Path(temp) / "bank")
                result = fill_template(directory, manifest).read_bytes()
                zd2 = parse_zd2_bytes(result)
                self.assertTrue(zd2.checksum_valid)
                original = parse_zd2_bytes((directory / f"bank-{count}.ZD2").read_bytes())
                for section in parse_elf32(original.data_chunk.data).sections:
                    if section.name != ".const":
                        self.assertEqual(original.data_chunk.data[section.offset:section.offset+section.size],
                                         zd2.data_chunk.data[section.offset:section.offset+section.size])
                record = index["banks"][str(count)]
                offset = record["weights_offset"]
                weights = b"".join(m[2] for m in models)
                self.assertEqual(result[offset:offset+len(weights)], weights)
                labels = [m[1] for m in models] + (["EMPTY"] if count == 1 else [])
                label_bytes = b"".join(v.encode("ascii").ljust(8, b"\0") for v in labels)
                offset = record["labels_offset"]
                self.assertEqual(result[offset:offset+len(label_bytes)], label_bytes)

    def test_tampered_template_and_escaped_range_are_refused(self):
        with tempfile.TemporaryDirectory() as temp:
            directory = Path(temp) / "templates"
            shutil.copytree(TEMPLATES, directory)
            path = directory / "bank-1.ZD2"
            raw = path.read_bytes()
            path.write_bytes(raw[:-1] + bytes([raw[-1] ^ 1]))
            manifest = prepare_bank(self.models(1), Path(temp) / "bank")
            with self.assertRaisesRegex(ValueError, "hash mismatch"):
                fill_template(directory, manifest)
            path.write_bytes(raw)
            index_path = directory / "index.json"
            index = json.loads(index_path.read_text())
            index["banks"]["1"]["weights_offset"] = 0
            index_path.write_text(json.dumps(index))
            with self.assertRaisesRegex(ValueError, "constant section"):
                fill_template(directory, manifest)
            self.assertFalse((manifest.parent / "build").exists())

    def test_stale_sources_and_changed_controls_are_refused(self):
        with tempfile.TemporaryDirectory() as temp:
            directory = Path(temp) / "templates"
            shutil.copytree(TEMPLATES, directory)
            manifest = prepare_bank(self.models(1), Path(temp) / "bank")
            config = json.loads(manifest.read_text())
            config["params"][-1]["default"] = 50
            manifest.write_text(json.dumps(config))
            with self.assertRaisesRegex(ValueError, "controls"):
                fill_template(directory, manifest)
            config["params"][-1]["default"] = 100
            manifest.write_text(json.dumps(config))
            index_path = directory / "index.json"
            index = json.loads(index_path.read_text())
            index["dsp_source_sha256"] = {}
            index_path.write_text(json.dumps(index))
            with self.assertRaisesRegex(ValueError, "DSP sources"):
                fill_template(directory, manifest)


if __name__ == "__main__":
    unittest.main()
